"" Vim-plug
call plug#begin('~/.vim/plugged')

" Remember to use single quotes

" essentials
"Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle'}
" themes
Plug 'morhetz/gruvbox'
" Status bar on bottom
"Plug 'bling/vim-airline'
"Plug 'vim-airline/vim-airline-themes'

call plug#end() 

"""""" Plugin Configuration
"" Specific theme
let g:gruvbox_italic=1
colorscheme gruvbox 
let g:gruvbox_constrast_dark="hard"

"""""" General Configuration
" Encoding
set encoding=utf-8

" Show line numbers 
set number      "linenumber
set ruler

" Basic settings
set bs=2        "backspace should work as we expect
set clipboard=unnamed "Clipboard
set laststatus=2 "Always display statusline
set cursorline "Highlight current line

" Color theme
syntax on
filetype plugin on

" Tab settings
set autoindent
set expandtab
set softtabstop=2
set shiftwidth=2    "tab size = 2
set shiftround      "when shifting non-aligned set of lines, align them to next tabstop

" Searching
set hlsearch    "hightlight search result
set incsearch   "show first match when start typing
set ignorecase  "ignore case-sensitive
set smartcase   "use case-sensitive if I use uppercase

" Hotkey
map <C-t> :NERDTreeToggle <cr>
noremap <A-k> :m -2 <cr>
noremap <A-j> :m +1 <cr>
let mapleader= ","
 map <leader>h :wincmd h<CR>
 map <leader>j :wincmd j<CR>
 map <leader>k :wincmd k<CR>
 map <leader>l :wincmd l<CR>

" Config theme
set t_Co=256
set background=dark
set guifont=Consolas:h12
if (has("termguicolors"))
    set termguicolors
endif
let base16colorspace=256 " Access colors in 256

" Turn on elite
let g:elite_mode=1

" Disable arrow movement, resize splits instead
if get(g:, 'elite_mode')
    nnoremap <Up>    :resize +2<CR>
    nnoremap <Down>  :resize -2<CR>
    nnoremap <Left>  :vertical resize -2<CR>
    nnoremap <Right> :vertical resize +2<CR>
endif

" Compiler
"" C/C++
function! CPPSET()
    set nowrap
    nnoremap <buffer> <F9> :w<cr>:!g++ -Wall -Wextra -O2 -std=c++11 % -o %< -I ./<cr>
endfunction

"" LaTeX
function! TeXSET()
    set nowrap
    nnoremap <buffer> <F9> :w<cr>:!latex -interaction=nonstopmode % ./<cr>
    nnoremap <buffer> <F8> :w<cr>:!pdflatex -synctex=1 -interaction=nonstopmode % ./<cr>
endfunction

autocmd FileType cpp call CPPSET()
autocmd FileType tex call TeXSET()
autocmd FileType gitcommit set tw=60
